name: Check Contracts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable  # Better maintained action
        with:
          components: rust-src

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-contract
        run: |
          # Check if already installed
          if ! command -v cargo-contract &> /dev/null; then
            cargo install cargo-contract --version "^3.2.0"
          fi

      - name: Cache cargo binaries
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          
          # Check and install b2sum if not cached
          if ! command -v b2sum &> /dev/null; then
            cargo install b2sum
          fi

      - name: Get workspace members
        id: get-members
        run: |
          members=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages | map(select(.source == null)) | map(.name) | join(" ")')
          echo "members=${members}" >> $GITHUB_OUTPUT

      - name: Check contracts
        run: |
          set -e  # Exit on error
          members="${{ steps.get-members.outputs.members }}"
          # List of packages to skip (libraries and usdt)
          SKIP_PACKAGES="chain-extension d9-chain-extension d9-burn-common d9-test-utils d9_usdt"
          
          for member in $members; do
            # Skip if it's in the skip list
            if [[ " $SKIP_PACKAGES " =~ " $member " ]]; then
              echo "Skipping package: $member"
              continue
            fi
            
            echo "::group::Checking $member"
            cargo contract check --manifest-path "$member/Cargo.toml"
            echo "::endgroup::"
          done
